version: '3.3'
services:
  api:
    build:
      context: api
    volumes:
      - ./api:/api
    ports:
      - 5000:5000

  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./front:/usr/share/nginx/html